export const products = [
  {
    name: "Paracetamol 500mg",
    description: "Pain reliever and fever reducer",
    price: 3.5,
    image: "https://example.com/images/paracetamol.jpg",
    images: [
      "https://example.com/images/paracetamol1.jpg",
      "https://example.com/images/paracetamol2.jpg",
    ],
    stock: 120,
    category: "Pain Relief",
    prescriptionRequired: false,
  },
  {
    name: "Amoxicillin 250mg",
    description: "Antibiotic for bacterial infections",
    price: 12.0,
    image: "https://example.com/images/amoxicillin.jpg",
    images: [
      "https://example.com/images/amoxicillin1.jpg",
      "https://example.com/images/amoxicillin2.jpg",
    ],
    stock: 60,
    category: "Antibiotics",
    prescriptionRequired: true,
  },
  {
    name: "Cetirizine 10mg",
    description: "Used for treating allergies and hay fever",
    price: 5.0,
    image: "https://example.com/images/cetirizine.jpg",
    images: [],
    stock: 80,
    category: "Allergy",
    prescriptionRequired: false,
  },
  {
    name: "Ibuprofen 400mg",
    description: "Anti-inflammatory and pain relief medicine",
    price: 4.75,
    image: "https://example.com/images/ibuprofen.jpg",
    images: ["https://example.com/images/ibuprofen1.jpg"],
    stock: 100,
    category: "Pain Relief",
    prescriptionRequired: false,
  },
  {
    name: "Metformin 500mg",
    description: "Used for managing type 2 diabetes",
    price: 15.25,
    image: "https://example.com/images/metformin.jpg",
    images: [
      "https://example.com/images/metformin1.jpg",
      "https://example.com/images/metformin2.jpg",
    ],
    stock: 50,
    category: "Diabetes",
    prescriptionRequired: true,
  },
];
