const Products = [
    {
        id: 1,
        title: "Vitamin C Tablets",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Supplements",
        description: "Boost immunity with high-quality Vitamin C tablets.",
        image: "/shop/img1.jpg",
        rating: 3,
    },
    {
        id: 2,
        title: "Digital Thermometer",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Devices",
        description: "Accurate digital thermometer for daily health checks.",
        image: "/shop/img2.jpg",
        rating: 4,
    },
    {
        id: 3,
        title: "First Aid Kit",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Health Essentials",
        description: "Compact first aid kit for emergencies.",
        image: "/shop/img7.jpg",
        rating: 4,
    },
    {
        id: 4,
        title: "Pain Relief Balm",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Medicines",
        description: "Effective balm for joint and muscle pain.",
        image: "/shop/img8.jpg",
        rating: 5,
    },
    {
        id: 5,
        title: "Allergy Relief Tablets",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Medicines",
        description: "Fast-acting tablets to relieve allergy symptoms.",
        image: "/shop/img9.jpg",
        rating: 3,
    },
    {
        id: 6,
        title: "Hair Fall Control Oil",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Personal Care",
        description: "Strengthens hair roots and reduces hair fall.",
        image: "/shop/img10.jpg",
        rating: 4,
    },
    {
        id: 7,
        title: "Travel Medicine Pouch",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Health Essentials",
        description: "Compact pouch for organizing medicines on the go.",
        image: "/shop/img8.jpg",
        rating: 3,
    },
    {
        id: 8,
        title: "Eye Drops - Moisturizing",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Eye Care",
        description: "Soothes dry and irritated eyes.",
        image: "/shop/img7.jpg",
        rating: 5,
    },
    {
        id: 9,
        title: "Sunscreen Lotion SPF 50",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Skin Care",
        description: "High-protection sunscreen lotion for daily use.",
        image: "/shop/img6.jpg",
        rating: 4,
    },
    {
        id: 10,
        title: "Multivitamin Gummies",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Supplements",
        description: "Tasty multivitamin gummies for all ages.",
        image: "/shop/img5.jpg",
        rating: 5,
    },
    {
        id: 44,
        title: "Paracetamol 500mg",
        price: 25,
        originalPrice: 60,
        off: "58%",
        category: "Pain Relief",
        description: "Used for relief from fever and mild to moderate pain.",
        image: "/shop/img4.jpg",
        rating: 5,
    },
    {
        id: 45,
        title: "Cetirizine 10mg",
        price: 15,
        originalPrice: 40,
        off: "63%",
        category: "Allergy",
        description: "Antihistamine for allergic conditions like sneezing and hives.",
        image: "/shop/img3.jpg",
        rating: 4,
    },
    {
        id: 46,
        title: "ORS Sachet",
        price: 5,
        originalPrice: 10,
        off: "50%",
        category: "Hydration",
        description: "Oral rehydration salts for dehydration and diarrhea.",
        image: "/shop/img2.jpg",
        rating: 4,
    },
    {
        id: 47,
        title: "Volini Gel",
        price: 90,
        originalPrice: 130,
        off: "31%",
        category: "Pain Relief",
        description: "Topical pain relief for muscles and joints.",
        image: "/shop/img9.jpg",
        rating: 5,
    },
    {
        id: 48,
        title: "Dolo 650mg",
        price: 20,
        originalPrice: 50,
        off: "60%",
        category: "Pain Relief",
        description: "Effective against fever and body pain.",
        image: "/shop/img1.jpg",
        rating: 4,
    },
    {
        id: 49,
        title: "Band-Aid Strips",
        price: 30,
        originalPrice: 55,
        off: "45%",
        category: "First Aid",
        description: "Adhesive bandages for minor cuts and wounds.",
        image: "/shop/img10.jpg",
        rating: 4,
    },
    {
        id: 50,
        title: "Glucometer Strips (50 pcs)",
        price: 450,
        originalPrice: 700,
        off: "36%",
        category: "Diabetes Care",
        description: "Strips for home blood glucose testing.",
        image: "/shop/img4.jpg",
        rating: 5,
    },
    {
        id: 51,
        title: "Cough Syrup 100ml",
        price: 35,
        originalPrice: 80,
        off: "56%",
        category: "Cold & Cough",
        description: "Relieves cough, throat irritation, and congestion.",
        image: "/shop/img8.jpg",
        rating: 3,
    },
    {
        id: 52,
        title: "Digital Thermometer",
        price: 120,
        originalPrice: 200,
        off: "40%",
        category: "Medical Devices",
        description: "Easy-to-use digital thermometer for fever monitoring.",
        image: "/shop/img5.jpg",
        rating: 5,
    },
    {
        id: 53,
        title: "Vitamin C Tablets",
        price: 80,
        originalPrice: 150,
        off: "47%",
        category: "Supplements",
        description: "Boosts immunity and supports skin health.",
        image: "/shop/img1.jpg",
        rating: 4,
    },
    {
        id: 54,
        title: "Face Mask (Pack of 10)",
        price: 50,
        originalPrice: 90,
        off: "44%",
        category: "Covid Essentials",
        description: "Protective 3-ply face masks for daily use.",
        image: "/shop/img10.jpg",
        rating: 4,
    },
    {
        id: 55,
        title: "Hand Sanitizer 100ml",
        price: 25,
        originalPrice: 60,
        off: "58%",
        category: "Covid Essentials",
        description: "Kills 99.9% germs without water.",
        image: "/shop/img2.jpg",
        rating: 5,
    },
    {
        id: 56,
        title: "Zincovit Syrup",
        price: 55,
        originalPrice: 100,
        off: "45%",
        category: "Supplements",
        description: "Multivitamin tonic for kids and adults.",
        image: "/shop/img6.jpg",
        rating: 4,
    },
    {
        id: 57,
        title: "Loperamide Capsules",
        price: 18,
        originalPrice: 40,
        off: "55%",
        category: "Stomach Care",
        description: "Treats sudden diarrhea effectively.",
        image: "/shop/img1.jpg",
        rating: 3,
    },
    {
        id: 58,
        title: "N95 Respirator Mask",
        price: 70,
        originalPrice: 150,
        off: "53%",
        category: "Covid Essentials",
        description: "High-grade protection from airborne particles.",
        image: "/shop/img10.jpg",
        rating: 5,
    },
    {
        id: 59,
        title: "Diaper Rash Cream",
        price: 110,
        originalPrice: 180,
        off: "39%",
        category: "Baby Care",
        description: "Protects and soothes baby's skin.",
        image: "/shop/img9.jpg",
        rating: 4,
    },
    {
        id: 60,
        title: "Antacid Tablets",
        price: 30,
        originalPrice: 60,
        off: "50%",
        category: "Stomach Care",
        description: "Quick relief from acidity and indigestion.",
        image: "/shop/img5.jpg",
        rating: 4,
    },
    {
        id: 61,
        title: "Thermal Patches (Pack of 3)",
        price: 95,
        originalPrice: 150,
        off: "37%",
        category: "Pain Relief",
        description: "Heat therapy patches for back and joint pain.",
        image: "/shop/img2.jpg",
        rating: 4,
    },
    {
        id: 62,
        title: "Insulin Pen Needle Tips",
        price: 399,
        originalPrice: 550,
        off: "27%",
        category: "Diabetes Care",
        description: "Sterile tips for insulin pens.",
        image: "/shop/img1.jpg",
        rating: 5,
    },
    {
        id: 63,
        title: "Pregnancy Test Kit",
        price: 45,
        originalPrice: 90,
        off: "50%",
        category: "Feminine Care",
        description: "Fast and accurate results at home.",
        image: "/shop/img7.jpg",
        rating: 4,
    },
];

export default Products;
