const Products = [
    {
        id: 1,

        title: "Cool Sunglasses",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Accessories",
        description: "Stylish toy sunglasses for kids.",
        image: "/shop/img1.png",
        star: 3,
    },
    {
        id: 2,

        title: "Toy Watch",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Accessories",
        description: "Digital watch for pretend play.",
        image: "/shop/img2.png",
        star: 4,
    },
    {
        id: 3,

        title: "Mini Purse",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Accessories",
        description: "Colorful mini handbag.",
        image: "/shop/img7.png",
        star: 4,
    },
    {
        id: 4,

        title: "Kid's Necklace",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Accessories",
        description: "Shiny and safe necklace.",
        image: "/shop/img8.png",
        star: 5,
    },
    {
        id: 5,

        title: "Bracelet Pack",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Accessories",
        description: "Fun bracelet set.",
        image: "/shop/img9.png",
        star: 3,
    },
    {
        id: 6,

        title: "Stylish Hair Clip",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Accessories",
        description: "Bright hair clips.",
        image: "/shop/img12.png",
        star: 4,
    },
    {
        id: 7,

        title: "Mini Travel Backpack",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Accessories",
        description: "Small and cute backpack.",
        image: "/shop/img12.png",
        star: 3,
    },
    {
        id: 8,

        title: "Colorful Toy Glasses",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Accessories",
        description: "Colorful toy glasses.",
        image: "/shop/img12.png",
        star: 5,
    },
    {
        id: 9,

        title: "Fashion Dress Hat",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Accessories",
        description: "Mini hat for dress-up.",
        image: "/shop/img12.png",
        star: 4,
    },

    {
        id: 10,

        title: "Barbie Classic Doll",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Barbie",
        description: "Classic Barbie doll.",
        image: "/shop/img12.png",
        star: 5,
    },
    {
        id: 11,

        title: "Barbie Glam Doll",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Barbie",
        description: "Classic Barbie doll.",
        image: "/shop/img11.png",
        star: 4,
    },
    {
        id: 12,

        title: "Barbie Dreamhouse Set",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Barbie",
        description: "Large Barbie playhouse.",
        image: "/shop/img11.png",
        star: 5,
    },
    {
        id: 13,

        title: "Barbie Convertible Car",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Barbie",
        description: "Pink convertible toy car.",
        image: "/shop/img11.png",
        star: 4,
    },
    {
        id: 14,

        title: "Barbie Fashion Set",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Barbie",
        description: "Fashion clothes for Barbie.",
        image: "/shop/img11.png",
        star: 3,
    },
    {
        id: 15,

        title: "Barbie Mermaid Doll",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Barbie",
        description: "Mermaid-themed Barbie.",
        image: "/shop/img11.png",
        star: 5,
    },

    {
        id: 16,

        title: "Bear Princess Doll",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Bear",
        description: "Princess Barbie with crown.",
        image: "/shop/img11.png",
        star: 3,
    },
    {
        id: 17,

        title: "Royal Bear Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Bear",
        description: "Princess Barbie with crown.",
        image: "/shop/img11.png",
        star: 4,
    },
    {
        id: 18,

        title: "Elegant Bear Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Bear",
        description: "Princess Barbie with crown.",
        image: "/shop/img11.png",
        star: 5,
    },
    {
        id: 19,

        title: "Bear Princess Deluxe",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Bear",
        description: "Princess Barbie with crown.",
        image: "/shop/img11.png",
        star: 4,
    },
    {
        id: 20,

        title: "Golden Bear Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Bear",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 5,
    },
    {
        id: 21,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Fashion Kid",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 4,
    },
    {
        id: 22,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Bear",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 5,
    },
    {
        id: 23,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Bear",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 3,
    },
    {
        id: 24,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Bear",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 3,
    },
    {
        id: 25,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Bear",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 3,
    },
    {
        id: 26,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Bear",
        description: "Princess Barbie with crown.",
        image: "barbie6.jpg",
        star: 4,
    },
    {
        id: 27,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Bear",
        description: "Princess Barbie with crown.",
        image: "barbie6.jpg",
        star: 5,
    },
    {
        id: 28,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Jigsaw Puzzle",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 5,
    },
    {
        id: 29,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Stuffed Toys",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 4,
    },
    {
        id: 30,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Stuffed Toys",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 5,
    },
    {
        id: 31,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Feeding Set",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 4,
    },
    {
        id: 32,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Wooden Toys",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 4,
    },
    {
        id: 33,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Stuffed Toys",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 5,
    },
    {
        id: 34,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Stuffed Toys",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 3,
    },
    {
        id: 35,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Stuffed Toys",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 4,
    },
    {
        id: 36,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Stuffed Toys",
        description: "Princess Barbie with crown.",
        image: "/shop/img2.png",
        star: 3,
    },
    {
        id: 37,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Stuffed Toys",
        description: "Princess Barbie with crown.",
        image: "/shop/img8.png",
        star: 4,
    },
    {
        id: 39,

        title: "Barbie Princess",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Stuffed Toys",
        description: "Princess Barbie with crown.",
        image: "/shop/img8.png",
        star: 5,
    },
    {
        id: 40,

        title: "Teddy Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Toy & Game",
        description: "Soft brown teddy bear.",
        image: "/shop/img8.png",
        star: 4,
    },
    {
        id: 41,

        title: "Stroller Bear - Hug Me",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Strollers",
        description: "Big huggable bear.",
        image: "/shop/img8.png",
        star: 3,
    },
    {
        id: 42,

        title: "Stroller Bear - Snuggles",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Strollers",
        description: "Big huggable bear.",
        image: "/shop/img8.png",
        star: 4,
    },
    {
        id: 43,

        title: "Stroller Bear - Cozy Pal",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Strollers",
        description: "Big huggable bear.",
        image: "/shop/img8.png",
        star: 5,
    },
    {
        id: 44,

        title: "Stroller Bear - Little Hug",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Strollers",
        description: "Big huggable bear.",
        image: "/shop/img8.png",
        star: 4,
    },
    {
        id: 45,

        title: "Stroller Bear - Teddy Joy",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Strollers",
        description: "Big huggable bear.",
        image: "/shop/img8.png",
        star: 3,
    },
    {
        id: 46,

        title: "Stroller Bear - Bouncy Friend",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Strollers",
        description: "Big huggable bear.",
        image: "/shop/img8.png",
        star: 5,
    },
    {
        id: 47,

        title: "Stroller Bear - Furry Love",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Strollers",
        description: "Big huggable bear.",
        image: "/shop/img3.png",
        star: 4,
    },
    {
        id: 48,

        title: "Stroller Bear - Ride Buddy",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Strollers",
        description: "Big huggable bear.",
        image: "/shop/img3.png",
        star: 3,
    },
    {
        id: 49,

        title: "Stroller Bear - Baby’s Pal",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Strollers",
        description: "Big huggable bear.",
        image: "/shop/img3.png",
        star: 5,
    },
    {
        id: 50,

        title: "Stroller Bear - Sunshine Hug",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Jigsaw Puzzle",
        description: "Big huggable bear.",
        image: "/shop/img3.png",
        star: 4,
    },
    {
        id: 51,

        title: "Smart Toy - Baby Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        rating: 4.5,
        category: "Smart Toys",
        description: "Cute baby-sized bear.",
        image: "/shop/img3.png",
        star: 5,
    },
    {
        id: 52,

        title: "Smart Toy - Little Genius",
        price: 20,
        originalPrice: 120,
        off: "80%",
        rating: 4.5,
        category: "Smart Toys",
        description: "Cute baby-sized bear.",
        image: "/shop/img3.png",
        star: 4,
    },

    {
        id: 53,

        title: "Smart Toy - Clever Cub",
        price: 20,
        originalPrice: 120,
        off: "80%",
        rating: 4.5,
        category: "Wooden Toys",
        description: "Cute baby-sized bear.",
        image: "/shop/img11.png",
        review: "Great toy for early learning!",
    },
    {
        id: 54,

        title: "Smart Toy - Thinky Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        rating: 4.5,
        category: "Wooden Toys",
        description: "Cute baby-sized bear.",
        image: "/shop/img11.png",
        review: "Perfect for toddlers!",
    },
    {
        id: 55,

        title: "Smart Toy - Logic Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        rating: 4.5,
        category: "Wooden Toys",
        description: "Cute baby-sized bear.",
        image: "/shop/img11.png",
        review: "Helps develop logic skills.",
    },
    {
        id: 56,

        title: "Smart Toy - Techy Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        rating: 4.5,
        category: "Wooden Toys",
        description: "Cute baby-sized bear.",
        image: "/shop/img11.png",
        review: "A great tech-based toy!",
    },
    {
        id: 57,

        title: "Smart Toy - Edu Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        rating: 4.5,
        category: "Smart Toys",
        description: "Cute baby-sized bear.",
        image: "/shop/img11.png",
        review: "An amazing educational toy.",
    },
    {
        id: 58,

        title: "Smart Toy - Learn Buddy",
        price: 20,
        originalPrice: 120,
        off: "80%",
        rating: 4.5,
        category: "Smart Toys",
        description: "Cute baby-sized bear.",
        image: "/shop/img2.png",
        review: "Ideal for young learners.",
    },

    {
        id: 59,

        title: "Movement Bear - White Dash",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Movement Toys",
        description: "Fluffy white teddy.",
        image: "/shop/img12.png",
        review: "Perfect for active kids!",
    },
    {
        id: 60,

        title: "Movement Bear - Fast Fluff",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Movement Toys",
        description: "Fluffy white teddy.",
        image: "/shop/img12.png",
        review: "Super fun for energetic play.",
    },
    {
        id: 61,

        title: "Movement Bear - Zoom Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Movement Toys",
        description: "Fluffy white teddy.",
        image: "/shop/img12.png",
        review: "Great for racing games.",
    },
    {
        id: 62,

        title: "Movement Bear - Active Cub",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Jigsaw Puzzle",
        description: "Fluffy white teddy.",
        image: "/shop/img12.png",
        review: "A cub that moves and groves!",
    },
    {
        id: 63,

        title: "Movement Bear - Bop & Bounce",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Jigsaw Puzzle",
        description: "Fluffy white teddy.",
        image: "/shop/img12.png",
        review: "A fun bouncing bear for kids!",
    },
    {
        id: 64,

        title: "Movement Bear - Wiggle Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Movement Toys",
        description: "Fluffy white teddy.",
        image: "/shop/img3.png",
        review: "Wiggles all over!",
    },
    {
        id: 65,

        title: "Movement Bear - Go Buddy",
        price: 20,
        originalPrice: 120,
        off: "80%",
        category: "Movement Toys",
        description: "Fluffy white teddy.",
        image: "/shop/img3.png",
        review: "Go, buddy, go!",
    },
    {
        id: 66,

        title: "Movement Bear - Move Me",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Movement Toys",
        description: "Fluffy white teddy.",
        image: "/shop/img3.png",
        review: "Super active bear!",
    },
    {
        id: 67,

        title: "Movement Bear - Rolly Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Movement Toys",
        description: "Fluffy white teddy.",
        image: "/shop/img3.png",
        review: "Rolls all around the house.",
    },
    {
        id: 68,

        title: "Movement Bear - Zoomy Fluff",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Fashion Kid",
        description: "Fluffy white teddy.",
        image: "/shop/img3.png",
        review: "Zooms super fast!",
    },
    {
        id: 69,

        title: "Movement Bear - Skip Buddy",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Fashion Kid",
        description: "Fluffy white teddy.",
        image: "/shop/img3.png",
        review: "Perfect for skipping fun.",
    },
    {
        id: 70,

        title: "Movement Bear - Quick Hug",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Fashion Kid",
        description: "Fluffy white teddy.",
        image: "/shop/img8.png",
        review: "Gives the best hugs!",
    },

    {
        id: 71,

        title: "Market Bear - Bow Style",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Market",
        description: "Bear with red bow.",
        image: "/shop/img3.png",
        review: "Super stylish with a bow!",
    },
    {
        id: 72,

        title: "Market Bear - Sweet Bow",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Market",
        description: "Bear with red bow.",
        image: "/shop/img8.png",
        review: "Sweet and adorable.",
    },
    {
        id: 73,

        title: "Market Bear - Classic Red",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Market",
        description: "Bear with red bow.",
        image: "/shop/img8.png",
        review: "Classic red bear with a bow.",
    },
    {
        id: 74,

        title: "Market Bear - Ribbon Cub",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Market",
        description: "Bear with red bow.",
        image: "/shop/img8.png",
        review: "A ribbon cub for every season.",
    },
    {
        id: 75,

        title: "Market Bear - Festive Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Market",
        description: "Bear with red bow.",
        image: "/shop/img8.png",
        review: "Perfect for festive occasions!",
    },
    {
        id: 76,

        title: "Market Bear - Fancy Fur",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Market",
        description: "Bear with red bow.",
        image: "/shop/img8.png",
        review: "Fur is fancy and fun.",
    },
    {
        id: 77,

        title: "Market Bear - Gift Ready",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Market",
        description: "Bear with red bow.",
        image: "/shop/img8.png",
        review: "Great for gifting!",
    },

    {
        id: 78,

        title: "Lego Bear - Build Friend",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Feeding Set",
        description: "Plush stuffed bear.",
        image: "/shop/img8.png",
        review: "Perfect for LEGO lovers.",
    },
    {
        id: 79,

        title: "Lego Bear - Brick Buddy",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Feeding Set",
        description: "Plush stuffed bear.",
        image: "/shop/img8.png",
        review: "Great for building and cuddling!",
    },
    {
        id: 80,

        title: "Lego Bear - Stack Cub",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Feeding Set",
        description: "Plush stuffed bear.",
        image: "/shop/img8.png",
        review: "Fun stacking bear.",
    },
    {
        id: 81,

        title: "Lego Bear - Clicky Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Feeding Set",
        description: "Plush stuffed bear.",
        image: "/shop/img8.png",
        review: "Click and build!",
    },
    {
        id: 82,

        title: "Lego Bear - Builder Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Lego",
        description: "Plush stuffed bear.",
        image: "/shop/img8.png",
        review: "Perfect for young builders.",
    },
    {
        id: 83,

        title: "Lego Bear - Block Pal",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Lego",
        description: "Plush stuffed bear.",
        image: "/shop/img8.png",
        review: "A pal for your blocks.",
    },
    {
        id: 84,

        title: "Lego Bear - Puzzle Cub",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Lego",
        description: "Plush stuffed bear.",
        image: "/shop/img8.png",
        review: "Great for puzzle lovers.",
    },
    {
        id: 85,

        title: "Lego Bear - Tiny Builder",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Lego",
        description: "Plush stuffed bear.",
        image: "/shop/img8.png",
        review: "Tiny but mighty builder.",
    },
    {
        id: 86,

        title: "Lego Bear - Toy Bricks",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Lego",
        description: "Plush stuffed bear.",
        image: "/shop/img8.png",
        review: "Perfect for toy brick lovers.",
    },

    {
        id: 87,

        title: "Lego Bear - Tiny Builder",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Control Toys",
        description: "Plush stuffed bear.",
        image: "/shop/img8.png",
        review: "Ideal for controlling and building.",
    },
    {
        id: 88,

        title: "Lego Bear - Toy Bricks",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Control Toys",
        description: "Plush stuffed bear.",
        image: "/shop/img8.png",
        review: "For the ultimate control enthusiast.",
    },

    {
        id: 89,

        title: "Hair Clip Set",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Disney",
        description: "Bright hair clips.",
        image: "/shop/img8.png",
        review: "Perfect for little girls!",
    },
    {
        id: 90,

        title: "Mini Backpack",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Disney",
        description: "Small and cute backpack.",
        image: "/shop/img8.png",
        review: "Perfect size for a Disney lover.",
    },
    {
        id: 87,

        title: "Lego Bear - Tiny Builder",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Control Toys",
        description: "Plush stuffed bear.",
        image: "/shop/img8.png",
        review: "Ideal for controlling and building.",
    },
    {
        id: 91,

        title: "Lego Bear - Toy Bricks",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Control Toys",
        description: "Plush stuffed bear.",
        image: "/shop/img8.png",
        review: "For the ultimate control enthusiast.",
    },

    {
        id: 92,

        title: "Hair Clip Set",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Disney",
        description: "Bright hair clips.",
        image: "/shop/img8.png",
        review: "Perfect for little girls!",
    },
    {
        id: 93,

        title: "Mini Backpack",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Disney",
        description: "Small and cute backpack.",
        image: "/shop/img8.png",
        review: "Perfect size for a Disney lover.",
    },
    {
        id: 40,

        title: "Teddy Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Toy & Game",
        description: "Soft brown teddy bear.",
        image: "/shop/img6.png",
        star: 4,
    },
    {
        id: 40,

        title: "Teddy Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Toy & Game",
        description: "Soft brown teddy bear.",
        image: "/shop/img6.png",
        star: 4,
    },
    {
        id: 40,

        title: "Teddy Bear",
        price: 20,
        originalPrice: 120,
        off: "80%",
        cateory: "Toy & Game",
        description: "Soft brown teddy bear.",
        image: "/shop/img6.png",
        star: 4,
    },
];

export default Products;
